// https://github.com/wube/factorio-data/blob/master/core/lualib/collision-mask-defaults.lua
declare module "collision-mask-defaults" {
    interface MaskType {
        ["agricultural-tower"]: prototype.CollisionMaskConnector,
        ["ammo-turret"]: prototype.CollisionMaskConnector,
        ["arithmetic-combinator"]: prototype.CollisionMaskConnector,
        ["artillery-turret"]: prototype.CollisionMaskConnector,
        ["assembling-machine"]: prototype.CollisionMaskConnector,
        ["asteroid-chunk"]: prototype.CollisionMaskConnector,
        ["asteroid-collector"]: prototype.CollisionMaskConnector,
        ["asteroid"]: prototype.CollisionMaskConnector,
        ["beacon"]: prototype.CollisionMaskConnector,
        ["boiler"]: prototype.CollisionMaskConnector,
        ["burner-generator"]: prototype.CollisionMaskConnector,
        ["decider-combinator"]: prototype.CollisionMaskConnector,
        ["electric-energy-interface"]: prototype.CollisionMaskConnector,
        ["electric-turret"]: prototype.CollisionMaskConnector,
        ["fluid-turret"]: prototype.CollisionMaskConnector,
        ["furnace"]: prototype.CollisionMaskConnector,
        ["generator"]: prototype.CollisionMaskConnector,
        ["heat-interface"]: prototype.CollisionMaskConnector,
        ["infinity-pipe"]: prototype.CollisionMaskConnector,
        ["inserter"]: prototype.CollisionMaskConnector,
        ["lab"]: prototype.CollisionMaskConnector,
        ["market"]: prototype.CollisionMaskConnector,
        ["mining-drill"]: prototype.CollisionMaskConnector,
        ["offshore-pump"]: prototype.CollisionMaskConnector,
        ["pipe-to-ground"]: prototype.CollisionMaskConnector,
        ["pipe"]: prototype.CollisionMaskConnector,
        ["plant"]: prototype.CollisionMaskConnector,
        ["fusion-generator"]: prototype.CollisionMaskConnector,
        ["fusion-reactor"]: prototype.CollisionMaskConnector,
        ["power-switch"]: prototype.CollisionMaskConnector,
        ["programmable-speaker"]: prototype.CollisionMaskConnector,
        ["pump"]: prototype.CollisionMaskConnector,
        ["radar"]: prototype.CollisionMaskConnector,
        ["reactor"]: prototype.CollisionMaskConnector,
        ["rocket-silo-rocket-shadow"]: prototype.CollisionMaskConnector,
        ["rocket-silo-rocket"]: prototype.CollisionMaskConnector,
        ["selector-combinator"]: prototype.CollisionMaskConnector,
        ["simple-entity-with-force"]: prototype.CollisionMaskConnector,
        ["simple-entity-with-owner"]: prototype.CollisionMaskConnector,
        ["simple-entity"]: prototype.CollisionMaskConnector,
        ["storage-tank"]: prototype.CollisionMaskConnector,
        ["thruster"]: prototype.CollisionMaskConnector,
        ["tree"]: prototype.CollisionMaskConnector,
        ["turret"]: prototype.CollisionMaskConnector,
        ["unit-spawner"]: prototype.CollisionMaskConnector,
        ["valve"]: prototype.CollisionMaskConnector,
        ["wall"]: prototype.CollisionMaskConnector,
        ["display-panel"]: prototype.CollisionMaskConnector,

        ["accumulator"]: prototype.CollisionMaskConnector,
        ["cargo-pod"]: prototype.CollisionMaskConnector,
        ["constant-combinator"]: prototype.CollisionMaskConnector,
        ["electric-pole"]: prototype.CollisionMaskConnector,
        ["lamp"]: prototype.CollisionMaskConnector,
        ["solar-panel"]: prototype.CollisionMaskConnector,
        ["train-stop"]: prototype.CollisionMaskConnector,

        ["cargo-bay"]: prototype.CollisionMaskConnector,
        ["cargo-landing-pad"]: prototype.CollisionMaskConnector,
        ["lightning-attractor"]: prototype.CollisionMaskConnector,
        ["roboport"]: prototype.CollisionMaskConnector,
        ["rocket-silo"]: prototype.CollisionMaskConnector,
        ["space-platform-hub"]: prototype.CollisionMaskConnector,

        ["container"]: prototype.CollisionMaskConnector,
        ["infinity-container"]: prototype.CollisionMaskConnector,
        ["linked-container"]: prototype.CollisionMaskConnector,
        ["proxy-container"]: prototype.CollisionMaskConnector,
        ["logistic-container"]: prototype.CollisionMaskConnector,
        ["temporary-container"]: prototype.CollisionMaskConnector,

        ["linked-belt"]: prototype.CollisionMaskConnector,
        ["loader-1x1"]: prototype.CollisionMaskConnector,
        ["loader"]: prototype.CollisionMaskConnector,
        ["splitter"]: prototype.CollisionMaskConnector,
        ["lane-splitter"]: prototype.CollisionMaskConnector,
        ["transport-belt"]: prototype.CollisionMaskConnector,
        ["underground-belt"]: prototype.CollisionMaskConnector,

        ["curved-rail-a"]: prototype.CollisionMaskConnector,
        ["curved-rail-b"]: prototype.CollisionMaskConnector,
        ["half-diagonal-rail"]: prototype.CollisionMaskConnector,
        ["legacy-curved-rail"]: prototype.CollisionMaskConnector,
        ["legacy-straight-rail"]: prototype.CollisionMaskConnector,
        ["straight-rail"]: prototype.CollisionMaskConnector,

        ["rail-ramp"]: prototype.CollisionMaskConnector,
        ["rail-ramp/allow_on_deep_oil_ocean"]: prototype.CollisionMaskConnector,

        ["rail-support"]: prototype.CollisionMaskConnector,
        ["rail-support/allow_on_deep_oil_ocean"]: prototype.CollisionMaskConnector,

        ["elevated-curved-rail-a"]: prototype.CollisionMaskConnector,
        ["elevated-curved-rail-b"]: prototype.CollisionMaskConnector,
        ["elevated-half-diagonal-rail"]: prototype.CollisionMaskConnector,
        ["elevated-straight-rail"]: prototype.CollisionMaskConnector,

        ["rail-chain-signal"]: prototype.CollisionMaskConnector,
        ["rail-signal"]: prototype.CollisionMaskConnector,

        ["rail-chain-signal/elevated"]: prototype.CollisionMaskConnector,
        ["rail-signal/elevated"]: prototype.CollisionMaskConnector,

        ["artillery-wagon"]: prototype.CollisionMaskConnector,
        ["infinity-cargo-wagon"]: prototype.CollisionMaskConnector,
        ["cargo-wagon"]: prototype.CollisionMaskConnector,
        ["fluid-wagon"]: prototype.CollisionMaskConnector,
        ["locomotive"]: prototype.CollisionMaskConnector,

        ["artillery-wagon/transition"]: prototype.CollisionMaskConnector,
        ["infinity-cargo-wagon/transition"]: prototype.CollisionMaskConnector,
        ["cargo-wagon/transition"]: prototype.CollisionMaskConnector,
        ["fluid-wagon/transition"]: prototype.CollisionMaskConnector,
        ["locomotive/transition"]: prototype.CollisionMaskConnector,

        ["artillery-wagon/elevated"]: prototype.CollisionMaskConnector,
        ["infinity-cargo-wagon/elevated"]: prototype.CollisionMaskConnector,
        ["cargo-wagon/elevated"]: prototype.CollisionMaskConnector,
        ["fluid-wagon/elevated"]: prototype.CollisionMaskConnector,
        ["locomotive/elevated"]: prototype.CollisionMaskConnector,

        ["gate"]: prototype.CollisionMaskConnector,
        ["gate/opened"]: prototype.CollisionMaskConnector,

        ["arrow"]: prototype.CollisionMaskConnector,
        ["artillery-flare"]: prototype.CollisionMaskConnector,
        ["artillery-projectile"]: prototype.CollisionMaskConnector,
        ["beam"]: prototype.CollisionMaskConnector,
        ["capture-robot"]: prototype.CollisionMaskConnector,
        ["character-corpse"]: prototype.CollisionMaskConnector,
        ["combat-robot"]: prototype.CollisionMaskConnector,
        ["construction-robot"]: prototype.CollisionMaskConnector,
        ["explosion"]: prototype.CollisionMaskConnector,
        ["fire"]: prototype.CollisionMaskConnector,
        ["highlight-box"]: prototype.CollisionMaskConnector,
        ["item-request-proxy"]: prototype.CollisionMaskConnector,
        ["leaf-particle"]: prototype.CollisionMaskConnector,
        ["lightning"]: prototype.CollisionMaskConnector,
        ["logistic-robot"]: prototype.CollisionMaskConnector,
        ["particle-source"]: prototype.CollisionMaskConnector,
        ["particle"]: prototype.CollisionMaskConnector,
        ["projectile"]: prototype.CollisionMaskConnector,
        ["projectile/hit"]: prototype.CollisionMaskConnector,
        ["smoke-with-trigger"]: prototype.CollisionMaskConnector,
        ["smoke"]: prototype.CollisionMaskConnector,
        ["speech-bubble"]: prototype.CollisionMaskConnector,
        ["sticker"]: prototype.CollisionMaskConnector,
        ["stream"]: prototype.CollisionMaskConnector,
        ["tile"]: prototype.CollisionMaskConnector,

        ["car"]: prototype.CollisionMaskConnector,
        ["character"]: prototype.CollisionMaskConnector,
        ["character/flying"]: prototype.CollisionMaskConnector,
        ["cliff"]: prototype.CollisionMaskConnector,
        ["corpse"]: prototype.CollisionMaskConnector,
        ["deconstructible-tile-proxy"]: prototype.CollisionMaskConnector,
        ["entity-ghost"]: prototype.CollisionMaskConnector,
        ["fish"]: prototype.CollisionMaskConnector,
        ["heat-pipe"]: prototype.CollisionMaskConnector,
        ["item-entity"]: prototype.CollisionMaskConnector,
        ["land-mine"]: prototype.CollisionMaskConnector,
        ["player-port"]: prototype.CollisionMaskConnector,
        ["rail-remnants"]: prototype.CollisionMaskConnector,
        ["resource"]: prototype.CollisionMaskConnector,
        ["spider-leg"]: prototype.CollisionMaskConnector,
        ["spider-unit"]: prototype.CollisionMaskConnector,
        ["spider-vehicle"]: prototype.CollisionMaskConnector,
        ["tile-ghost"]: prototype.CollisionMaskConnector,
        ["unit"]: prototype.CollisionMaskConnector,
        ["segment"]: prototype.CollisionMaskConnector,
        ["segmented-unit"]: prototype.CollisionMaskConnector,
        ["decorative"]: prototype.CollisionMaskConnector,
    }

    const masks: MaskType;

    export default masks;
}