name: Create Release and NPM Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - index.d.ts
      - dist/*.d.ts
      - src/*.d.ts
      - tsconfig.base.json

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      # https://github.com/MetroStar/comet/blob/7a9cce0013196057881990aeddbaafdaa6c9fadc/.github/workflows/publish-package.yaml#L35
      - name: Update NPM
        run: npm install -g npm@latest
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: npm run validate
        run: npm run validate
      - name: npm pack
        run: npm pack
      - name: Read package.json
        id: read-package-json
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: Get current version
        id: current-version
        run: echo "PACKAGE_VERSION=${{ fromJson(steps.read-package-json.outputs.content).version}}" >> "$GITHUB_OUTPUT"
      - name: Get Factorio version
        id: factorio-version
        run: echo "FACTORIO_VERSION=${{ fromJson(steps.read-package-json.outputs.content).factorioVersion}}" >> "$GITHUB_OUTPUT"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "factorio-types-${{ steps.current-version.outputs.PACKAGE_VERSION }}.tgz"
          commit: master
          tag: v${{ steps.current-version.outputs.PACKAGE_VERSION }}
          name: v${{ steps.current-version.outputs.PACKAGE_VERSION }}
          body: Type definitions for Factorio v${{ steps.factorio-version.outputs.FACTORIO_VERSION }}
      - name: Publish to NPM
        run: npm publish