name: Pull Request CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - index.d.ts
      - dist/*.d.ts

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  pull-request-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: npm run copy-source
        run: npm run copy-source
      - name: npm run validate
        run: npm run validate
